name: repo_generation
description: A new Flutter project.
version: 0.0.3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  build: ^3.0.0
  build_config: ^1.1.2
  code_builder: ^4.10.1
  better_repo_annotation: ^0.0.3
  source_gen: ^3.1.0

dev_dependencies:
  build_test: ^2.2.3
  build_runner: ^2.4.14



